//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandProperties.Repositories.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LandPropertiesDBEntities : DbContext
    {
        public LandPropertiesDBEntities()
            : base("name=LandPropertiesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LAND_PROPERTY> LAND_PROPERTY { get; set; }
        public DbSet<MORTGAGE> MORTGAGEs { get; set; }
        public DbSet<OWNER> OWNERs { get; set; }
    }
}
