//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandProperties.Repositories.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAND_PROPERTY
    {
        public LAND_PROPERTY()
        {
            this.MORTGAGEs = new HashSet<MORTGAGE>();
        }
    
        public int ID { get; set; }
        public int OWNER_ID { get; set; }
        public double AREA { get; set; }
        public string UPI { get; set; }
    
        public virtual OWNER OWNER { get; set; }
        public virtual ICollection<MORTGAGE> MORTGAGEs { get; set; }
    }
}
