//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandProperties.Repositories.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MORTGAGE
    {
        public int ID { get; set; }
        public int LAND_PROPERTY_ID { get; set; }
        public decimal MONEY_AMOUNT { get; set; }
        public System.DateTime BEGIN_DATE { get; set; }
    
        public virtual LAND_PROPERTY LAND_PROPERTY { get; set; }
    }
}
