//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandProperties.Repositories.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWNER
    {
        public OWNER()
        {
            this.LAND_PROPERTY = new HashSet<LAND_PROPERTY>();
        }
    
        public int ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual ICollection<LAND_PROPERTY> LAND_PROPERTY { get; set; }
    }
}
