//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandProperties.OwnerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Owner", Namespace="http://schemas.datacontract.org/2004/07/LandProperties.Entities")]
    [System.SerializableAttribute()]
    public partial class Owner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LandProperties.OwnerService.LandProperty> LandPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LandProperties.OwnerService.LandProperty> LandProperties {
            get {
                return this.LandPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.LandPropertiesField, value) != true)) {
                    this.LandPropertiesField = value;
                    this.RaisePropertyChanged("LandProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LandProperty", Namespace="http://schemas.datacontract.org/2004/07/LandProperties.Entities")]
    [System.SerializableAttribute()]
    public partial class LandProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LandProperties.OwnerService.Mortgage> MortgagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LandProperties.OwnerService.Owner OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LandProperties.OwnerService.Mortgage> Mortgages {
            get {
                return this.MortgagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MortgagesField, value) != true)) {
                    this.MortgagesField = value;
                    this.RaisePropertyChanged("Mortgages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandProperties.OwnerService.Owner Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPI {
            get {
                return this.UPIField;
            }
            set {
                if ((object.ReferenceEquals(this.UPIField, value) != true)) {
                    this.UPIField = value;
                    this.RaisePropertyChanged("UPI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mortgage", Namespace="http://schemas.datacontract.org/2004/07/LandProperties.Entities")]
    [System.SerializableAttribute()]
    public partial class Mortgage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BeginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginDate {
            get {
                return this.BeginDateField;
            }
            set {
                if ((this.BeginDateField.Equals(value) != true)) {
                    this.BeginDateField = value;
                    this.RaisePropertyChanged("BeginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyAmount {
            get {
                return this.MoneyAmountField;
            }
            set {
                if ((this.MoneyAmountField.Equals(value) != true)) {
                    this.MoneyAmountField = value;
                    this.RaisePropertyChanged("MoneyAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OwnerService.IOwnerService")]
    public interface IOwnerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOwnerService/GetAllOwners", ReplyAction="http://tempuri.org/IOwnerService/GetAllOwnersResponse")]
        System.Collections.Generic.List<LandProperties.OwnerService.Owner> GetAllOwners();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOwnerService/GetAllOwners", ReplyAction="http://tempuri.org/IOwnerService/GetAllOwnersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LandProperties.OwnerService.Owner>> GetAllOwnersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOwnerService/Save", ReplyAction="http://tempuri.org/IOwnerService/SaveResponse")]
        LandProperties.OwnerService.Owner Save(LandProperties.OwnerService.Owner owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOwnerService/Save", ReplyAction="http://tempuri.org/IOwnerService/SaveResponse")]
        System.Threading.Tasks.Task<LandProperties.OwnerService.Owner> SaveAsync(LandProperties.OwnerService.Owner owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOwnerService/GetOwner", ReplyAction="http://tempuri.org/IOwnerService/GetOwnerResponse")]
        LandProperties.OwnerService.Owner GetOwner(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOwnerService/GetOwner", ReplyAction="http://tempuri.org/IOwnerService/GetOwnerResponse")]
        System.Threading.Tasks.Task<LandProperties.OwnerService.Owner> GetOwnerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOwnerService/Delete", ReplyAction="http://tempuri.org/IOwnerService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOwnerService/Delete", ReplyAction="http://tempuri.org/IOwnerService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOwnerServiceChannel : LandProperties.OwnerService.IOwnerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OwnerServiceClient : System.ServiceModel.ClientBase<LandProperties.OwnerService.IOwnerService>, LandProperties.OwnerService.IOwnerService {
        
        public OwnerServiceClient() {
        }
        
        public OwnerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OwnerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OwnerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OwnerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<LandProperties.OwnerService.Owner> GetAllOwners() {
            return base.Channel.GetAllOwners();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LandProperties.OwnerService.Owner>> GetAllOwnersAsync() {
            return base.Channel.GetAllOwnersAsync();
        }
        
        public LandProperties.OwnerService.Owner Save(LandProperties.OwnerService.Owner owner) {
            return base.Channel.Save(owner);
        }
        
        public System.Threading.Tasks.Task<LandProperties.OwnerService.Owner> SaveAsync(LandProperties.OwnerService.Owner owner) {
            return base.Channel.SaveAsync(owner);
        }
        
        public LandProperties.OwnerService.Owner GetOwner(int id) {
            return base.Channel.GetOwner(id);
        }
        
        public System.Threading.Tasks.Task<LandProperties.OwnerService.Owner> GetOwnerAsync(int id) {
            return base.Channel.GetOwnerAsync(id);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
